import {
    REDUCER_ACTION_REQUEST,
    REDUCER_ACTION_SUCCESS,
    REDUCER_ACTION_RESET,
    REDUCER_ACTION_FAIL
  } from '../types';
  
  export const TYPE_REGISTER = 'registerCreate';
  
  export const REGISTER_REQUEST = `${TYPE_REGISTER}/${REDUCER_ACTION_REQUEST}`;
  export const REGISTER_SUCCESS = `${TYPE_REGISTER}/${REDUCER_ACTION_SUCCESS}`;
  export const REGISTER_RESET = `${TYPE_REGISTER}/${REDUCER_ACTION_RESET}`;
  export const REGISTER_FAIL = `${TYPE_REGISTER}/${REDUCER_ACTION_FAIL}`;
